import type { SchemaItem } from "./types";

export const SCHEMA: readonly SchemaItem[] = [
    { key: "neck", label: "NECK", type: "select", allowedValues: ["ROUND NECK", "V NECK", "POLO NECK", "HENLEY", "CREW"] },
    { key: "neck_type", label: "NECK TYPE", type: "select", allowedValues: ["RIB", "PLAIN", "TAPED", "DOUBLE LAYER", "CONTRAST"] },
    { key: "neck_size", label: "NECK SIZE", type: "select", allowedValues: [".25\"", ".5\"", ".75\""] },
    { key: "placket", label: "PLACKET", type: "select", allowedValues: ["RIB PLKT", "PLN PLKT"] },
    { key: "sleeve", label: "SLEEVE", type: "select", allowedValues: ["HALF SLEEVE", "FULL SLEEVE", "SLEEVELESS", "3/4TH"] },
    { key: "fit", label: "FIT", type: "select", allowedValues: ["REGULAR", "SLIM", "OVERSIZED", "RELAXED"] },
    { key: "pattern", label: "PATTERN", type: "select", allowedValues: ["SOLID", "STRIPE", "AOP", "PRINTED", "TEXTURED", "EMBROIDERED"] },
    { key: "length", label: "LENGTH", type: "select", allowedValues: ["CROP", "REGULAR", "LONG"] },
    { key: "hem_style", label: "HEM STYLE", type: "select", allowedValues: ["STRAIGHT", "CURVED", "ASYMMETRIC"] },
    { key: "drawcord", label: "DRAWCORD", type: "select", allowedValues: ["YES", "NO"] },
    { key: "drawcord_style", label: "DRAWCORD STYLE", type: "select", allowedValues: ["FLAT", "ROUND"] },
    { key: "pocket_type", label: "POCKET TYPE", type: "select", allowedValues: ["NONE", "PATCH", "KANGAROO", "SIDE SEAM"] },
    { key: "fab_type", label: "FAB TYPE", type: "select", allowedValues: ["SINGLE JERSEY", "PIQUE", "RIB", "INTERLOCK", "SLUB"] },
    { key: "composition", label: "COMPOSITION", type: "select", allowedValues: ["100% COTTON", "COTTON POLY BLEND", "POLYESTER", "ORGANIC COTTON", "MODAL BLEND"] },
    { key: "gsm", label: "GSM", type: "select", allowedValues: ["120-140", "160-180", "200-240"] },
    { key: "shade", label: "SHADE", type: "select", allowedValues: ["LIGHT", "MEDIUM", "DARK"] },
    { key: "print_type", label: "PRINT TYPE", type: "select", allowedValues: ["SCREEN", "DIGITAL", "PUFF", "FOIL"] },
    { key: "print_placement", label: "PRINT PLACEMENT", type: "select", allowedValues: ["CHEST", "ALL OVER", "BACK", "SLEEVE"] },
    { key: "print_style", label: "PRINT STYLE", type: "select", allowedValues: ["GRAPHIC", "TYPOGRAPHY", "PHOTO", "LOGO"] },
    { key: "embroidery", label: "EMBROIDERY", type: "select", allowedValues: ["NONE", "CHEST LOGO", "BADGE", "PATCHWORK"] },
    { key: "wash", label: "WASH", type: "select", allowedValues: ["BIO", "STONE", "ACID", "ENZYME", "NONE"] },
    { key: "wash_color", label: "WASH COLOR", type: "select", allowedValues: ["TONE ON TONE", "CONTRAST"] },
    { key: "color", label: "COLOR", type: "select", allowedValues: ["WHITE", "BLACK", "NAVY", "GREY", "RED", "GREEN", "YELLOW", "BEIGE", "MULTI"] },
    { key: "size", label: "SIZE", type: "select", allowedValues: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"] },
    { key: "buying_type", label: "BUYING_TYPE", type: "select", allowedValues: ["NORMAL", "PROMOTIONAL", "CORE"] },
    { key: "article_type", label: "ARTICLE TYPE", type: "select", allowedValues: ["BASIC", "FASHION", "SEASONAL"] },
];
